---
- name: prolauno playbook Letras
  hosts: letras
  become: yes

  vars_prompt:
    - name: domain_member_admin_user
      prompt: Qual seu número USP?

    - name: domain_member_password
      prompt: Qual sua senha?

  tasks:

    - name: Aplica role fflch.tasks
      include_role:
        name: fflch.tasks

    - name: Configura resolv.conf para consultar DNSs do firstdc dev
      include_role:
        name: blackstar257.resolv
      vars:
        resolv_conf_nameservers:
          - 143.107.72.180
        resolv_conf_search_domains:
          - "smbdomain.fflch.usp.br"

    - name: fflch.domain-member
      include_role:
        name: fflch.domain-member
      vars:
        domain_member_realm: "smbdomain.fflch.usp.br"
        domain_member_samba_server: sambadc180
        
    - name: proaluno role
      include_role:
        name: fflch.proaluno
      vars:
        proaluno_deploy_printers: True
        proaluno_install_pacotes_debian: True
        proaluno_install_mate: True
        proaluno_remove_all_printers: True
        proaluno_update_keys: True
        proaluno_cups_server: "ipp://cups.fflch.usp.br:631/printers"
        proaluno_sala: "proaluno_letras_"
        proaluno_printers:
          - name: impressora
            device: "{{ proaluno_cups_server }}/proaluno_letras_ppd"
            model: 'K7600_processado_gstopdf17.ppd'

